// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Analyzes draft copy for AI-like patterns and suggests edits to improve authenticity and flow.
 *
 * - aiSignatureAnalyzer - A function that handles the analysis and suggestion process.
 * - AiSignatureAnalyzerInput - The input type for the aiSignatureAnalyzer function.
 * - AiSignatureAnalyzerOutput - The return type for the aiSignatureAnalyzer function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiSignatureAnalyzerInputSchema = z.object({
  draftCopy: z.string().describe('The draft copy to analyze for AI-like patterns.'),
});
export type AiSignatureAnalyzerInput = z.infer<typeof AiSignatureAnalyzerInputSchema>;

const AiSignatureAnalyzerOutputSchema = z.object({
  suggestions: z.array(z.string()).describe('A list of suggestions to improve authenticity and flow.'),
  analysis: z.string().describe('An analysis of the AI-like patterns found in the draft copy.'),
});
export type AiSignatureAnalyzerOutput = z.infer<typeof AiSignatureAnalyzerOutputSchema>;

export async function aiSignatureAnalyzer(input: AiSignatureAnalyzerInput): Promise<AiSignatureAnalyzerOutput> {
  return aiSignatureAnalyzerFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiSignatureAnalyzerPrompt',
  input: {schema: AiSignatureAnalyzerInputSchema},
  output: {schema: AiSignatureAnalyzerOutputSchema},
  prompt: `You are an AI writing signature analyzer. You will analyze the draft copy provided and suggest edits to improve authenticity and flow.

Draft Copy: {{{draftCopy}}}

Analyze the draft copy for AI-like patterns and suggest edits to improve authenticity and flow. Provide a list of suggestions and an analysis of the AI-like patterns found in the draft copy.

Output the suggestions and analysis in the following JSON format:
{
  "suggestions": ["suggestion 1", "suggestion 2", "suggestion 3"],
  "analysis": "analysis of AI-like patterns"
}
`,
});

const aiSignatureAnalyzerFlow = ai.defineFlow(
  {
    name: 'aiSignatureAnalyzerFlow',
    inputSchema: AiSignatureAnalyzerInputSchema,
    outputSchema: AiSignatureAnalyzerOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
