version: '3.8'

services:
  ai-studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-studio-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # 应用配置
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      # Google Gemini API 配置（可选，用户可通过网站界面配置）
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    env_file:
      - .env
    volumes:
      # 如果需要持久化数据，可以挂载卷
      - app-data:/app/data
    restart: unless-stopped
    networks:
      - ai-studio-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：如果需要 Nginx 反向代理
  # nginx:
  #   image: nginx:alpine
  #   container_name: ai-studio-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - ai-studio
  #   restart: unless-stopped
  #   networks:
  #     - ai-studio-network

volumes:
  app-data:
    driver: local

networks:
  ai-studio-network:
    driver: bridge
